### ISSUE TITLE
Ubuntu 20.04 (nagadomi/distro) install_lua_modules.sh error

### ISSUE THREAD

**Issue by idanka** [nagadomi/waifu2x#337]
Warning: variable CFLAGS was not passed in build_variables
make -C deps/http-parser library
make[1]: Entering directory '/tmp/luarocks_turbo-2.1-2-430/turbo/deps/http-parser'
gcc  -I. -fPIC -DHTTP_PARSER_STRICT=0  -O3  -Wall -Wextra -c http_parser.c -o libhttp_parser.o
gcc  -shared -Wl,-soname=libhttp_parser.so.2.1 -o libhttp_parser.so.2.1 libhttp_parser.o
make[1]: Leaving directory '/tmp/luarocks_turbo-2.1-2-430/turbo/deps/http-parser'
gcc -Ideps/http-parser/ -shared -O3 -Wall -g  -fPIC deps/http-parser/libhttp_parser.o deps/turbo_ffi_wrap.c -o libtffi_wrap.so  -lcrypto -lssl
In file included from deps/turbo_ffi_wrap.c:32:
deps/turbo_ffi_wrap.h:22:10: fatal error: openssl/ssl.h: Nincs ilyen fájl vagy könyvtár
 #include <openssl/ssl.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:88: all] Error 1

Error: Build error: Failed building.

**Comment by nagadomi** [comment]
You need to install libssl-dev package, but turbo.lua may not be able to build with libssl on Ubuntu 20.04. https://github.com/kernelsauce/turbo/issues/343 I have not test it.
If you do not need the web server interface, you do not need to install turbo.lua. So you can ignore the error.

**Comment by idanka** [comment]
ok, and Turbo install
PREFIX=$HOME/torch/install luarocks install turbo
